image: python:3.11.0
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
  - $CI_PROJECT_DIR/.cache/pip
before_script:
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate
- apt-get update -yq
- apt-get install -y build-essential libffi-dev python3-dev
- pip install poetry
- poetry add ruff
- export PATH="/root/.local/bin:$PATH"
stages:
- linting
linting:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - black --check
    - ruff
