image: python:3.11.0
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DJANGO_SECRET_KEY : test_key
  DB_NAME : "postgres"
  DB_USER : "postgres"
  DB_PASSWORD : "123"
  DB_HOST : "localhost"
  DB_PORT : "5432"
  DEBUG : "True"
  ALLOWED_HOSTS : "*"
before_script:
  - python -m venv venv
  - source venv/bin/activate
  - python -V
  - pip install poetry
  - poetry install --no-root
  - export PATH="/root/.local/bin:$PATH"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - linting
  - test

lint_black:
  stage: linting
  script:
    - black --check .

lint_ruff:
  stage: linting
  script:
    - ruff .

test:
    stage: test
    script:
      - python store/manage.py test
