image: python:3.11.0
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
  - ".cache/pip"
  - venv/
before_script:
- python -m venv venv
- source venv/bin/activate
- pip install poetry
- poetry add ruff
- export PATH="/root/.local/bin:$PATH"
stages:
- linting
linting:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - black --check
    - ruff
