image: python:3.11.0
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
  - $CI_PROJECT_DIR/.cache/pip
before_script:
- python -m pip install --upgrade pip
- pip install virtualenv
- virtualenv venv
- apk update
- apk add --no-cache build-base libffi-dev
- source venv/bin/activate
- pip install poetry
- poetry add ruff
- export PATH="/root/.local/bin:$PATH"
stages:
- linting
linting:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - black --check
