version: "3.9"

services:
  sneakers_db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=sneakers_db
        - POSTGRES_USER=db_user
        - POSTGRES_PASSWORD=123

  redis:
    image: redis
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery -A /python_docker/store/config worker -l info
    volumes:
      - .:/python_docker
    depends_on:
        - sneakers_db
        - redis
  celery-beat:
    build: .
    command: celery -A /python_docker/store/config beat -l info
    volumes:
      - .:/python_docker
    depends_on:
        - sneakers_db
        - redis
  django:
    container_name: django_app
    build:
      context: .
      dockerfile: Dockerfile
    command:
      bash -c "python /python_docker/store/manage.py makemigrations &&
      python /python_docker/store/manage.py migrate &&
      python /python_docker/store/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/python_docker
    ports:
      - 8000:8000
    depends_on:
      - sneakers_db
      - redis
volumes:
    postgres_data:
