# Generated by Django 4.2 on 2023-04-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsblog',
            options={'verbose_name': 'News Blog', 'verbose_name_plural': 'News Blog'},
        ),
        migrations.RemoveField(
            model_name='newsblog',
            name='description',
        ),
        migrations.AddField(
            model_name='newsblog',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
